server:
  port: 10080 # 服务端口


spring:

  autoconfigure: # 排除数据库自动配置
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${eduexch.nacos.host}:${eduexch.nacos.port} # nacos发现地址
      config:
        server-addr: ${eduexch.nacos.host}:${eduexch.nacos.port} # nacos配置中心地址

    gateway:
      routes:
        # 规则. 注意微服务是根据单体拆的, 路径存在不规范
        #        - id: admin-service # 必须唯一路由标识
        #          uri: lb://adminservice # 路由的目标地址
        #          predicates: # 路由断言，判断请求是否符合规则
        #            - Path=/admin/**
        #          filters:
        #            - AddRequestHeader=Authorization, "Bearer {token}"

        # 测试请把请求统一发送到这个网关服务地址, 进行路由转发

        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/admin/panel/supply/**

        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/admin/employee/**

        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/customer/admin/**

        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/customer/guest/**


        # guest-service
        - id: guest-service
          uri: lb://guest
          predicates:
            - Path=/admin/user/**

        - id: guest-service
          uri: lb://guest
          predicates:
            - Path=/guest/user/**


        # supply-service
        - id: supply-service
          uri: lb://supply
          predicates:
            - Path=/admin/panel/supply/**

        - id: supply-service
          uri: lb://supply
          predicates:
            - Path=/admin/prod/**

        - id: supply-service
          uri: lb://supply
          predicates:
            - Path=/guest/prod/**


        # trade-service
        - id: trade-service
          uri: lb://trade
          predicates:
            - Path=/admin/order/**

        - id: trade-service
          uri: lb://trade
          predicates:
            - Path=/guest/order/**

        - id: trade-service
          uri: lb://trade
          predicates:
            - Path=/admin/voucher/**

        - id: trade-service
          uri: lb://trade
          predicates:
            - Path=/guest/voucher/**


      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost" # 允许跨域请求
            allowedMethods: "*" # 允许所有的跨域ajax的请求方式
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

  profiles:
    active: dev   # 环境 dev|test|prod

  main:

    allow-circular-references: true # 允许循环引用
    allow-bean-definition-overriding: true # 允许覆盖bean定义
    lazy-initialization: false # 关闭懒加载, 防止组件失效

  # Redis
  data:
    redis:
      host: ${eduexch.redis.host}
      port: ${eduexch.redis.port}
      password: ${eduexch.redis.password}
      database: ${eduexch.redis.database}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 20000            # 超时时间: 20s


# 日志配置
logging:

  level:
    org.shop:
      DEBUG

  pattern:
    dateformat: mm:ss.SSS


# 自定义
eduexch:



# 禁止监控
management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false


# springdoc
springdoc:
  # swagger
  swagger-ui:
    path: admin.html # http://localhost:8085/admin.html



# feign
feign:
  okhttp:
    enabled: true # 开启连接池
  client:
    config:
      default:
        loggerLevel: FULL #  日志级别



# 网关白名单路径
auth:
  exclude-paths:
    - /admin.html
    - /admin/employee/login
    - /admin/employee/register
    - /admin/employee/code
    - /guest.html
    - /guest/user/login
    - /guest/user/register
    - /guest/user/code
    - /swagger-ui/**
    - /swagger-ui.html
    - /doc.html
    - /webjars/**
    - /swagger-resources/**
    - /v3/**
    - /error
