server:
  port: 10080 # 服务端口


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


  application:
    name: gateway

  cloud:
    nacos:
      server-addr: ${eduexch.nacos.host}:${eduexch.nacos.port} # nacos服务地址

  profiles:
    active: dev   # 环境 dev|test|prod

  main:

    allow-circular-references: true # 允许循环引用
    allow-bean-definition-overriding: true # 允许覆盖bean定义
    lazy-initialization: false # 关闭懒加载, 防止组件失效

  # Redis
  data:
    redis:
      host: ${eduexch.redis.host}
      port: ${eduexch.redis.port}
      password: ${eduexch.redis.password}
      database: ${eduexch.redis.database}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 20000            # 超时时间: 20s


# 日志配置
logging:

  level:
    com.shop:
      DEBUG

  pattern:
    dateformat: mm:ss.SSS


# 自定义
eduexch:


# 禁止 Actuator 监控 Redis 连接
management:
  health:
    redis:
      enabled: false

# springdoc
springdoc:
  # swagger
  swagger-ui:
    path: admin.html # http://localhost:8085/admin.html



# feign
feign:
  okhttp:
    enabled: true # 开启连接池
  client:
    config:
      default:
        loggerLevel: FULL #  日志级别
